
---
title: "Jar leak Test"
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: cerulean
    highlight: haddock
    smart: false
editor_options: 
  chunk_output_type: inline
---


Hello World

Author: OA Lab, NWFSC
Title: Reading Meta data for Krill Towing Data
Date: September 2021


# Version Check
```{r 0.1 Version Check , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Version Check
#********************************* 
R.version

```



# 1.) Libraries
```{r 0.0 Libraries , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
##Libraries
#********************************* 
library(stringr)
library(tidyverse)
library(plyr)
library(nlme)
library(tidyr)
library(dbplyr)
library(dplyr)
library(purrr)
library(wql)
library(lubridate)
library(tibbletime)
#for graphing
library(ggplot2)
library(ggfortify)
library(stringr)
library(nlme)
library(RColorBrewer)
library(patchwork)
#statistical analysis
# library(gdata)
# library(rsq)
# library(doBy)
# library(lme4)
# library(lmerTest)
#Rnotebooks 
library(gridExtra)
library(kableExtra)
library(todor)
library(knitr)
#metadata
library(metacsv)

```



# 2.) Creating Dataframes and new CSV documents 
```{r Creating Dataframes and new CSV documents }

#*********************************
## 2.) Creating Dataframes and new CSV documents
#*********************************

jarTest <- read_csv(here::here("raw_Data", "jarLeak", "SpecData(jarLeakTrial_ID_3jarID).csv"))

bottleMAP <- read_csv(here::here("raw_Data", "jarLeak", "BottleSalinityMap.csv"))

jarMAP <- read_csv(here::here("raw_Data", "jarLeak", "jarBottleMap.csv"))

# TODO missing six measurements
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

```



# 3.) Data cleaning
```{r 2.) Data cleaning}

jarTest$date <- as.POSIXct(jarTest$date, format="%m/%d/%y")

jarTest$jarID <- ""
jarTest$jarID <-
jarTest$jarID <- jarTest$id_3

unique(jarTest$jarID)
#  [1] "LoCO2_30AUG21" "J3C"           "J3D"           "J3L"          
#  [5] "J3K"           "J2A"           "J3F"           "J3B"          
#  [9] "J3H"           "J2H"           "J2B"           "J3A"          
# [13] "JD1"           "JA1"           "JC1"           "J2G"          
# [17] "J3E"           "J3G"           "J2D"           "J2E"          
# [21] "J2F"           "CH09_01"       "CH10_01"       "CH10_02"      
# [25] "CH10_03"       "CH09_03"       "CH10_03a"      "CH09_03a"     
# [29] "CH09_04"       "CH10_04" 

# 55 observations
#TODO 55 SPEC samples taken, not 56?
# want to only have Jar IDs with all other values as "N/A"
# 
# jarTest[order(jarTest[,'JarID']), ]

# jarTest <- jarTest %>% mutate(jarID=case_when(
#                           (jarID == "LoCO2_30AUG21") ~"N/A",
#                           (jarID == "CH09_01") ~"N/A",
#                           (jarID == "CH10_01") ~"N/A",
#                           (jarID == "CH10_02") ~"N/A",
#                           (jarID == "CH09_03") ~"N/A",
#                           (jarID == "CH10_03") ~"N/A",
#                           (jarID == "CH10_03a") ~"N/A",
#                           (jarID == "CH09_04") ~"N/A",
#                           (jarID == "CH10_04") ~"N/A",
#                           TRUE ~ jarTest$jarID %>% select(contains("J"))
#                         )
#                     ) 
  
```





#### 3.2) Fun with Plots
```{r Fun with Plots by treatment}

jarTest.summary <- jarTest %>% group_by(treatment) %>%
  dplyr::summarize(sd = sd(pHinsitu, na.rm = TRUE), 
            mean = mean(pHinsitu, na.rm = TRUE), 
            median = median(pHinsitu, na.rm = TRUE),
            IQR = IQR(pHinsitu, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd/sqrt(n)) %>%
  mutate(ci = se*1.96)
jarTest.summary


jarTest.summary_boxplot <- ggplot(jarTest, aes(treatment, pHinsitu)) +
            # geom_jitter(color = "grey") +
            geom_jitter(data = jarTest, aes(treatment, pHinsitu)) +
            geom_boxplot(notch = TRUE, outlier.shape = NA, colour = "green") +
            geom_point(data = jarTest.summary, aes(x=treatment, y=mean), size=5, color = "purple") + 
            geom_errorbar(data = jarTest.summary, 
                          aes(x=treatment, y=mean, ymin = mean-sd, ymax = mean+sd), 
                          color = "blue") +
            geom_errorbar(data = jarTest.summary,
                          aes(x=treatment, y=mean, ymin = mean-ci, ymax = mean+ci),
                          colour = "red") +
            # # facet_wrap(~placeholder) +
            # xlab("Treatment") +
            # ylab("non-Corrected pH") +
            # ggtitle("pH insitu across treatments") +
            theme_bw() 

jarTest.summary_boxplot


# Calculate pHinsitu Average for each bottle
# what I expect CH10 = 7.5196436, CH09= 7.81287312

subsetCH09_startbottle <- subset(jarSPEC, date == "8/27/21" & unit_ID == "Chamber_9")
bottle_9 <- mean(subsetCH09_startbottle$pHinsitu)
print(bottle_9)
# [1] 7.812873

subsetCH10_startbottle <- subset(jarSPEC, date == "8/27/21" & unit_ID == "Chamber_10")
bottle_10 <- mean(subsetCH10_startbottle$pHinsitu)
print(bottle_10)    
# [1] 7.519644

subsetCH09_jarSPECs <- subset(jarSPEC, date == "8/30/21" & unit_ID == "Chamber_09")

jarSPEC.summary_boxplot <- ggplot(jarSPEC, aes(treatOther, pHinsitu)) +
            # geom_jitter(color = "grey") +
            geom_point(data = jarSPEC, aes(treatOther, pHinsitu)) +
            abline(h=subsetCH09_startbottle)
            # # facet_wrap(~placeholder) +
            # xlab("Treatment") +
            # ylab("non-Corrected pH") +
            # ggtitle("non Temperature Corrected pH across Brands") +
            theme_bw() 

jarSPEC.summary_boxplot


```



# 4.) Jar Test Summary
```{r  Jar Test Summary}

jarTest$pH_of_sample_without_correction <- as.numeric(jarTest$pH_of_sample_without_correction)


jarTest.summary <- jarTest %>% group_by(Treatment) %>%
  dplyr::summarize(sd = sd(pH_of_sample_without_correction, na.rm = TRUE), 
            mean = mean(pH_of_sample_without_correction, na.rm = TRUE), 
            median = median(pH_of_sample_without_correction, na.rm = TRUE),
            IQR = IQR(pH_of_sample_without_correction, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd/sqrt(n)) %>%
  mutate(ci = se*1.96)
jarTest.summary


jarTest.summary_boxplot <- ggplot(jarTest, aes(Treatment, pH_of_sample_without_correction)) +
            # geom_jitter(color = "grey") +
            geom_jitter(data = jarTest, aes(Treatment, pH_of_sample_without_correction)) +
            geom_boxplot(notch = TRUE, outlier.shape = NA, colour = "green") +
            geom_point(data = jarTest.summary, aes(x=Treatment, y=mean), size=5, color = "purple") + 
            geom_errorbar(data = jarTest.summary, 
                          aes(x=Treatment, y=mean, ymin = mean-sd, ymax = mean+sd), 
                          color = "blue") +
            geom_errorbar(data = jarTest.summary,
                          aes(x=Treatment, y=mean, ymin = mean-ci, ymax = mean+ci),
                          colour = "red") +
            # # facet_wrap(~placeholder) +
            # xlab("Treatment") +
            # ylab("non-Corrected pH") +
            # ggtitle("non Temperature Corrected pH across Brands") +
            theme_bw() 

jarTest.summary_boxplot

kable(jarTest.summary, digits = 4)
write.csv(jarTest.summary, "ISO_KRL_jarTest.summary.csv")


```




### 4.1) Jar Test Plots
```{r Jar test plots}

# Creating four separate means from the blank vials per trial

x1 <- droplevels(filter(jarTest, Manufacturer != "N/A"))

x1.jarTest.summary <- x1 %>% group_by(Treatment) %>%
  dplyr::summarize(sd = sd(pH_of_sample_without_correction, na.rm = TRUE), 
            mean = mean(pH_of_sample_without_correction, na.rm = TRUE), 
            median = median(pH_of_sample_without_correction, na.rm = TRUE),
            IQR = IQR(pH_of_sample_without_correction, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd/sqrt(n)) %>%
  mutate(ci = se*1.96)
x1.jarTest.summary 


jarTest.summary_boxplot2 <- ggplot(jarTest, aes(Treatment, pH_of_sample_without_correction)) +
            # geom_jitter(color = "grey") +
            # geom_jitter(data = jarTest, aes(Treatment, pH_of_sample_without_correction)) +
            geom_jitter(aes(colour = Manufacturer)) +
            
            # # facet_wrap(~TrialID) +
            # xlab("Treatment") +
            # ylab("µg O2 h -1 g -1") +
            # ggtitle("Corrected Slope Summary Plot") +
            theme_bw() 

jarTest.summary_boxplot2



jarTest.summary_boxplot3 <- ggplot(jarTest, aes(Treatment, pH_of_sample_without_correction)) +
            # geom_jitter(color = "grey") +
            # geom_jitter(data = jarTest, aes(Treatment, pH_of_sample_without_correction)) +
            geom_jitter(aes(colour = insertType)) +
            
            # # facet_wrap(~TrialID) +
            # xlab("Treatment") +
            # ylab("µg O2 h -1 g -1") +
            # ggtitle("Corrected Slope Summary Plot") +
            theme_bw() 

jarTest.summary_boxplot3



```



5.) jarSPEC results & Summary

```{r  JarSPEC_Test Summary}

jarSPEC$pHinsitu <- as.numeric(jarSPEC$pHinsitu)


jarSPEC.summary <- jarSPEC %>% group_by(Treatment) %>%
  dplyr::summarize(sd = sd(pHinsitu, na.rm = TRUE), 
            mean = mean(pHinsitu, na.rm = TRUE), 
            median = median(pHinsitu, na.rm = TRUE),
            IQR = IQR(pHinsitu, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd/sqrt(n)) %>%
  mutate(ci = se*1.96)
jarTest.summary


jarTest.summary_boxplot <- ggplot(jarTest, aes(Treatment, pH_of_sample_without_correction)) +
            # geom_jitter(color = "grey") +
            geom_jitter(data = jarTest, aes(Treatment, pH_of_sample_without_correction)) +
            geom_boxplot(notch = TRUE, outlier.shape = NA, colour = "green") +
            geom_point(data = jarTest.summary, aes(x=Treatment, y=mean), size=5, color = "purple") + 
            geom_errorbar(data = jarTest.summary, 
                          aes(x=Treatment, y=mean, ymin = mean-sd, ymax = mean+sd), 
                          color = "blue") +
            geom_errorbar(data = jarTest.summary,
                          aes(x=Treatment, y=mean, ymin = mean-ci, ymax = mean+ci),
                          colour = "red") +
            # # facet_wrap(~placeholder) +
            # xlab("Treatment") +
            # ylab("non-Corrected pH") +
            # ggtitle("non Temperature Corrected pH across Brands") +
            theme_bw() 

jarTest.summary_boxplot

kable(jarTest.summary, digits = 4)
write.csv(jarTest.summary, "ISO_KRL_jarTest.summary.csv")



```{r}
#**************E*N*D*************# 
#*********************************
## END OF SCRIPT | END OF DOCUMENT 
#*********************************
```


## END OF SCRIPT | END OF DOCUMENT


